### ISSUE TITLE
Make Connections Visible by Default

### ISSUE THREAD

**Issue by acidicgaseouscloud** [firinael/obsidian-friendly-theme#1]
Hey! I love the theme and it's absolutely gorgeous! I just wanted to ask if it would be possible to make the connections in Obsidian's graph view apparent without requiring hovering? i.e. appear as below by default?

<img width="271" alt="Screenshot 2022-05-17 at 20 34 52" src="https://user-images.githubusercontent.com/56796730/168885727-567e9fb0-0db6-4eb7-8dcf-d2654769d14c.png">

**Comment by firinael** [comment]
Oh hey, sure! I never use the graph so I wasn't even aware that that wasn't the case by default. Will do something about it right now.

**Comment by firinael** [comment]
There we go, the graph lines now use `--text-faint` as color. If you'd like me to address anything else, feel free to open some more issues!

**Comment by acidicgaseouscloud** [comment]
Thank you so much <3333 !!
